"""Home Assistant entrypoint for Chihiros LED Core.

Home Assistant imports this domain module directly.  The implementation lives
in the LED plugin; these exports keep the required HA boundary and established
integration imports stable.
"""

from .plugins.led.integration import (
    ADD_SCHEDULE_SCHEMA,
    ATTR_ACTIVE,
    ATTR_ADDRESS,
    ATTR_BRIGHTNESS,
    ATTR_DEBUG,
    ATTR_END,
    ATTR_ENTITY_ID,
    ATTR_ENTRY_ID,
    ATTR_LEVELS,
    ATTR_PERIODS,
    ATTR_RAMP_UP_MINUTES,
    ATTR_SEND,
    ATTR_START,
    ATTR_WEEKDAYS,
    ENABLE_AUTO_MODE_SCHEMA,
    REMOVE_SCHEDULE_SCHEMA,
    RESET_SCHEDULE_SCHEMA,
    SERVICE_ADD_SCHEDULE,
    SERVICE_ENABLE_AUTO_MODE,
    SERVICE_REMOVE_SCHEDULE,
    SERVICE_RESET_SCHEDULE,
    SERVICE_SET_BRIGHTNESS,
    SERVICE_SET_SCHEDULE,
    SET_BRIGHTNESS_SCHEMA,
    SET_SCHEDULE_SCHEMA,
    async_setup,
    async_setup_entry,
    async_unload_entry,
)

__all__ = [
    "ADD_SCHEDULE_SCHEMA",
    "ATTR_ACTIVE",
    "ATTR_ADDRESS",
    "ATTR_BRIGHTNESS",
    "ATTR_DEBUG",
    "ATTR_END",
    "ATTR_ENTITY_ID",
    "ATTR_ENTRY_ID",
    "ATTR_LEVELS",
    "ATTR_PERIODS",
    "ATTR_RAMP_UP_MINUTES",
    "ATTR_SEND",
    "ATTR_START",
    "ATTR_WEEKDAYS",
    "ENABLE_AUTO_MODE_SCHEMA",
    "REMOVE_SCHEDULE_SCHEMA",
    "RESET_SCHEDULE_SCHEMA",
    "SERVICE_ADD_SCHEDULE",
    "SERVICE_ENABLE_AUTO_MODE",
    "SERVICE_REMOVE_SCHEDULE",
    "SERVICE_RESET_SCHEDULE",
    "SERVICE_SET_BRIGHTNESS",
    "SERVICE_SET_SCHEDULE",
    "SET_BRIGHTNESS_SCHEMA",
    "SET_SCHEDULE_SCHEMA",
    "async_setup",
    "async_setup_entry",
    "async_unload_entry",
]
