"""Compatibility exports for the LED coordinator."""

from .plugins.led.coordinator import (
    ATTR_FIRMWARE_VERSION,
    ATTR_LAST_NOTIFICATION,
    ATTR_RECENT_NOTIFICATIONS,
    ATTR_RUNTIME_MINUTES,
    ATTR_RUNTIME_NOTIFICATION,
    ATTR_RUNTIME_NOTIFICATION_PAYLOAD,
    ATTR_SCHEDULE_POINTS,
    ChihirosDataUpdateCoordinator,
)

__all__ = [
    "ATTR_FIRMWARE_VERSION",
    "ATTR_LAST_NOTIFICATION",
    "ATTR_RECENT_NOTIFICATIONS",
    "ATTR_RUNTIME_MINUTES",
    "ATTR_RUNTIME_NOTIFICATION",
    "ATTR_RUNTIME_NOTIFICATION_PAYLOAD",
    "ATTR_SCHEDULE_POINTS",
    "ChihirosDataUpdateCoordinator",
]
